[tool.poetry]
name = "morph-service"
version = "0.1.0"
description = ""
authors = ["r3d5un <r3d5un@pm.me>"]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
